name: CI-CD to Kubernetes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  IMAGE_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/final-flask
  IMAGE_TAG: sha-${{ github.sha }}
  K8S_NAMESPACE: default

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_REPO }}:latest

      - name: Write kubeconfig from secret
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Deploy manifests
        run: |
          kubectl apply -n "${K8S_NAMESPACE}" -f k8s/deployment.yaml
          kubectl apply -n "${K8S_NAMESPACE}" -f k8s/service.yaml

      - name: Update deployment image to the new tag
        run: |
          kubectl set image -n "${K8S_NAMESPACE}" deployment/final-flask final-flask="${IMAGE_REPO}:${IMAGE_TAG}"

      - name: Wait for rollout
        run: |
          kubectl rollout status -n "${K8S_NAMESPACE}" deployment/final-flask --timeout=120s

      - name: Show service info
        run: |
          kubectl get svc -n "${K8S_NAMESPACE}" final-flask -o wide
